// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpqznyoxualpyrtbqlkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwcXpueW94dWFscHlydGJxbGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTk3NjEsImV4cCI6MjA3MzU5NTc2MX0.XfA98Zw_nhiSvqsIrmtXRw3fJlYE2a4ExNMhapb2hck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});